In [1]:
import numpy as np 
np.full((2,3),5) 

array([[5, 5, 5],
       [5, 5, 5]])

In [3]:
first = np.array([1,2,3])

In [11]:
second= np.array([4,5,6]);

first.T

array([1, 2, 3])

In [23]:
finding_determinant=np.linalg.inv(np.arange(0,4).reshape(2,2))
finding_determinant

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

Accessing the values in array!!!!

In [20]:
np.identity(3)
finding_determinant=np.linalg.det(np.arange(0,4).reshape(2,2));

finding_determinant

-2.0

In [39]:
arr=np.array((1,2,3,4,12,4,6,5))

print(arr[-1])#printing the last element of the array

arr=np.array(((1,2,3),(4,5,6)))
print(arr[1,-1])

arr=np.array((((1,2,3)),(4,5,6),(7,8,9)))



5
6


Slicing of array

In [64]:
array = np.array((1,2,3,4,5));
#First element is not printing here!
print(array[1:4])
print(array[1:4]);
print(array[4:]);
array[1:5:2]


array = np.array((1,2,3,4,5),dtype="S");
array.dtype #String is datatype.


array=np.array(('1','2','3','4','5','6'),dtype="i")
array.shape

array = np.array((((1,2,3,4,5),(5,3,2,3,4),(5,3,234,1,2))));

# Lovely Method in python!!!!
# for i in array:
#   for j in i:
#    print(j)


# splitting method in python

array=np.array(('1','2','3','4','5','6'))
print(np.array(np.array_split(array,3))) # 3 mean how many rows you actually want    


[2 3 4]
[2 3 4]
[5]
[['1' '2']
 ['3' '4']
 ['5' '6']]


In [83]:
from numpy import array
data=array([
    [1,2,3,4],
    [4,5,6,7],
    [6,43,42,3]]
)

split=2
train,test=data[:split],data[split:]
print(train,"New thigns")
print(test)


[[1 2 3 4]
 [4 5 6 7]] New thigns
[[ 6 43 42  3]]


Let's talk about pandas!!!!! YEah Funny and amazing !

In [86]:
import pandas as pd

dataset={
    'cars':['suzuki',"hunda","cruise"],
    'price':[150000,123444,900000],
}

dataset = pd.DataFrame(dataset)
dataset

cars   price
0  suzuki  150000
1   hunda  123444
2  cruise  900000

In [91]:
dataset.head()
dataset.describe()


price
count       3.000000
mean   391148.000000
std    440878.751713
min    123444.000000
25%    136722.000000
50%    150000.000000
75%    525000.000000
max    900000.000000

converting rows to column and column to rows

In [101]:
data=np.array([1,3,3,3,4,5])
data
column=pd.Series(data)
row=data.T
print(column)
print("Working perfect")
print(row)

0    1
1    3
2    3
3    3
4    4
5    5
dtype: int64
Working perfect
[1 3 3 3 4 5]


Location and iloc functions in pandas!

In [118]:
print(dataset)
# print(dataset.loc[0],"seprating the rows")
# print(dataset.iloc[0],"separating")
print(dataset.loc[[0,1]])

     cars   price
0  suzuki  150000
1   hunda  123444
2  cruise  900000
     cars   price
0  suzuki  150000
1   hunda  123444
